#!/bin/sh -e

# create the log directory if it doesn't exist
[ -d /var/log/gonano/hoarder ] || mkdir -p /var/log/gonano/hoarder %>

# tell svlogd to drop the stdout into our custom location
cd /var/log/gonano/hoarder
exec svlogd -v -ttt /var/log/gonano/hoarder
