#!/bin/sh -e

# create the log directory if it doesn't exist
[ -d /var/log/gomicro/hoarder ] || mkdir -p /var/log/gomicro/hoarder

# tell svlogd to drop the stdout into our custom location
cd /var/log/gomicro/hoarder
exec svlogd -v -ttt /var/log/gomicro/hoarder
