#!/bin/sh -e

# create the log directory if it doesn't exist
[ -d /var/log/gomicro/slurp ] || mkdir -p /var/log/gomicro/slurp

# tell svlogd to drop the stdout into our custom location
cd /var/log/gomicro/slurp
exec svlogd -v -ttt /var/log/gomicro/slurp
