#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gomicro/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

if File.exist?('/opt/gomicro/etc/narc.conf')
  # create the runit definitions for narc
  directory '/etc/service/narc' do
    recursive true
  end

  directory '/etc/service/narc/log' do
    recursive true
  end

  hook_file '/etc/service/narc/log/run' do
    source 'runit/narc-log'
    mode 0755
  end

  hook_file '/etc/service/narc/run' do
    source 'runit/narc'
    mode 0755
  end

  service 'narc' do
    action :enable
  end
end

# create the runit definitions for hoarder
directory '/etc/service/hoarder' do
  recursive true
end

directory '/etc/service/hoarder/log' do
  recursive true
end

hook_file '/etc/service/hoarder/log/run' do
  source 'runit/hoarder-log'
  mode 0755
end

hook_file '/etc/service/hoarder/run' do
  source 'runit/hoarder'
  mode 0755
end

service 'hoarder' do
  action :enable
end

# create the runit definitions for slurp
directory '/etc/service/slurp' do
  recursive true
end

directory '/etc/service/slurp/log' do
  recursive true
end

hook_file '/etc/service/slurp/log/run' do
  source 'runit/slurp-log'
  mode 0755
end

hook_file '/etc/service/slurp/run' do
  source 'runit/slurp'
  mode 0755
end

service 'slurp' do
  action :enable
end
