#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Stop hoarder
service 'hoarder' do
  action :disable
end

# Remove hoarder runit definition
directory '/etc/service/hoarder' do
  action :delete
end

# Stop slurp
service 'slurp' do
  action :disable
end

# Remove slurp runit definition
directory '/etc/service/slurp' do
  action :delete
end

# Stop narc
service 'narc' do
  action :disable
end

# Remove narc runit definition
directory '/etc/service/narc' do
  action :delete
end
