#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

local_hoarder_md5 = execute "local hoarder md5" do
  command "cat /var/nanobox/hoarder.md5"
  not_if { ! ::File.exists? "/var/nanobox/hoarder.md5" }
end

aws_hoarder_md5 = execute "aws hoarder md5" do
  command <<-END 
    curl \
      -f \
      -k \
      https://d3ep67zochz54j.cloudfront.net/hoarder/linux/amd64/hoarder.md5 \
        | tee /tmp/hoarder.md5
  END
end

if local_hoarder_md5 != aws_hoarder_md5

  # Stop hoarder
  service 'hoarder' do
    action :disable
    not_if { !Dir.exist?('/etc/service/hoarder') }
  end

  execute "Download hoarder" do
    command <<-END 
      curl \
        -f \
        -k \
        -o /usr/local/bin/hoarder \
        https://d3ep67zochz54j.cloudfront.net/hoarder/linux/amd64/hoarder
    END
  end

  execute "Chmod hoarder" do
    command "chmod 755 /usr/local/bin/hoarder"
  end

  service 'hoarder' do
    action :enable
    not_if { !Dir.exist?('/etc/service/hoarder') }
  end

  execute "Finalize update" do
    command "mv /tmp/hoarder.md5 /var/nanobox/hoarder.md5"
  end
end

local_slurp_md5 = execute "local slurp md5" do
  command "cat /var/nanobox/slurp.md5"
  not_if { ! ::File.exists? "/var/nanobox/slurp.md5" }
end

aws_slurp_md5 = execute "aws slurp md5" do
  command <<-END 
    curl \
      -f \
      -k \
      https://d3ep67zochz54j.cloudfront.net/slurp/linux/amd64/slurp.md5 \
        | tee /tmp/slurp.md5
  END
end

if local_slurp_md5 != aws_slurp_md5

  # Stop slurp
  service 'slurp' do
    action :disable
    not_if { !Dir.exist?('/etc/service/slurp') }
  end

  execute "Download slurp" do
    command <<-END 
      curl \
        -f \
        -k \
        -o /usr/local/bin/slurp
        https://d3ep67zochz54j.cloudfront.net/slurp/linux/amd64/slurp
    END
  end

  execute "Chmod slurp" do
    command "chmod 755 /usr/local/bin/slurp"
  end

  service 'slurp' do
    action :enable
    not_if { !Dir.exist?('/etc/service/slurp') }
  end

  execute "Finalize update" do
    command "mv /tmp/slurp.md5 /var/nanobox/slurp.md5"
  end
end

local_hooks_md5 = execute "local hooks md5" do
  command "cat /var/nanobox/hooks.md5"
  not_if { ! ::File.exists? "/var/nanobox/hooks.md5" }
end

aws_hooks_md5 = execute "aws hooks md5" do
  command <<-END
    curl \
      -f \
      -k \
      https://d1ormdui8qdvue.cloudfront.net/hooks/hoarder-stable.md5 \
        | tee /var/nanobox/hooks.md5
  END
end

if local_hooks_md5 != aws_hooks_md5
  execute "update hooks" do
    command <<-END
      curl \
        -f \
        -k \
        https://d1ormdui8qdvue.cloudfront.net/hooks/hoarder-stable.tgz \
          | tar -xz -C /opt/nanobox/hooks
    END
  end
end
